Add JAXB API to the test class path
This is required to be able to test against Java 11. In Java 11, JAXB is
removed from the JDK (See http://openjdk.java.net/jeps/320). This commit
fixes errors of type:

```
StaxEventItemWriterTests.java:22: error: package javax.xml.bind.annotation
does not exist: import javax.xml.bind.annotation.XmlRootElement;
```

Two important points (from JEP 320) to note about this commit:

* `Another risk of removing the Java EE modules is that applications
 which already migrated from JDK 6, 7, or 8, to JDK 9, will not start if
 they use the command line flag --add-modules java.se.ee,
 --add-modules java.xml.bind, etc.` This commit removes the need to add
 the flag `--add-modules java.xml.bind`. This removal does not impact
 building on Java 9 since JAXB is in the class path now.

 * `The Reference Implementations (RIs) of JAX-WS and JAXB are a good
 starting point because they are complete replacements for the
 java.xml.ws and java.xml.bind modules in JDK 9. The RIs are available
 as Maven artifacts: (note that they must be deployed on the class path)`
 This commit adds JAXB to the test class path where needed.

Issue: BATCH-2757