Retry on generating unique identifiers with MongoDB
This commit will mitigate write conflict:

```
org.springframework.dao.DataIntegrityViolationException: Command failed with error 112 (WriteConflict):
'Caused by :: Write conflict during plan execution and yielding is disabled. :: Please retry your operation or multi-document transaction.' on server xxx.mongodb.net:1026.
[...]
```

Typically, only transient errors are retried, and even if `DataIntegrityViolationException` extends `NonTransientDataAccessException`,
this commit retries the operation as requested by the MongoDB driver (`Please retry your operation or multi-document transaction`).

Closes GH-4960

Signed-off-by: Yanming Zhou <zhouyanming@gmail.com>
(cherry picked from commit eac1ff5e85b5b22d841dcfce62afc87e233ce762)